name: Lint and Comment
on: pull_request

permissions:
  pull-requests: write

jobs:
  lint_and_comment:
    name: Lint and Comment
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Run SwiftFormat
        id: swiftformat_lint
        run: |
          swiftformat --lint --swiftversion 5.0 . --reporter github-actions-log | tee swiftformat_output.txt
        continue-on-error: true

      - name: Check if SwiftFormat Lint Found Issues
        id: check_lint_issues
        run: |
          if grep -q "error:" swiftformat_output.txt; then
            echo "lint_issues=true" >> $GITHUB_ENV
          else
            echo "lint_issues=false" >> $GITHUB_ENV
          fi

      - name: Post SwiftFormat Lint Result
        if: env.lint_issues == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: swiftformat-lint-result
          message: |
            👋🏼 Hey there! It looks like SwiftFormat found some things that need attention.

            Don’t worry, these are just formatting issues. Here’s what SwiftFormat found:

            ```
            ${{ steps.swiftformat_lint.outputs.stdout }}
            ```

            You can easily fix these issues by running SwiftFormat locally. If you haven't installed it yet, you can do so by following the instructions [here](https://github.com/nicklockwood/SwiftFormat#command-line-tool).

            Once installed, just run the following command in your project directory:

            ```
            swiftformat .
            ```

            This will automatically apply the necessary formatting. After that, commit the changes, and you should be good to go! 😊

            Thanks for your effort and for keeping the codebase clean and consistent!
